name: Gitleaks

on:

  push:
    branches: 
      - master
      - main
      - develop
      - development
      - qa
      
  pull_request:
    branches: 
      - master
      - main
      - develop
      - development
      - qa

jobs:
  key_leak-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
          
      - name: Gitleaks
        run: |
          GO111MODULE=on go get github.com/zricethezav/gitleaks/v7
          pwd | $HERE
          gitleaks --path=$HERE -v --no-git
